### ISSUE TITLE
Crash with loading world

### ISSUE THREAD

**Issue by SeanChengN** [unascribed/PopcornSmelting#4] opened 2018-10-23 02:38 UTC
Just loading world...
Crash report: https://pastebin.com/h5zLdr3z

Mod version: 1.5

**Comment by Cynosphere** [comment] 2018-10-23 03:28
From what I can gather, the crash is from another mod most likely having an invalid smelting result. I can't tell what mod it would be without recreating your exact instance and testing myself.

If you know of mods that have smelting recipes added off the top of your head, try disabling them one at a time and trying until you find the culprit.

**Comment by SeanChengN** [comment] 2018-10-23 04:23
> From what I can gather, the crash is from another mod most likely having an invalid smelting result. I can't tell what mod it would be without recreating your exact instance and testing myself.
> 
> If you know of mods that have smelting recipes added off the top of your head, try disabling them one at a time and trying until you find the culprit.

Well, I tried it again and again, but it didn't reproduce it. May be a random issue.

**Comment by exaskye** [comment] 2018-10-23 04:37
The only way this could happen is a mod injecting furnace recipes on-the-fly **in another thread**, which is a Very Bad Thing that should Never Be Done.

It's very hard to know which mod is doing it; ConcurrentModificationExceptions are *hard* to debug.

**Comment by exaskye** [comment] 2018-10-23 04:39
There isn't really a sane way for me to fix this, and since it's caused by another mod doing *unbelievably bad things*, I'll be closing it.

**Closed as completed by exaskye** 2018-10-23 04:39 UTC
Labels: k: Not Our Defect
